version: '3.8'
services:
  flashbrain-backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    deploy:
      resources:
        limits:
          memory: 512M # Giới hạn cứng RAM
        reservations:
          memory: 128M
    restart: always